package harness_test

import (
	"bufio"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"
)

const alwaysLoadedLineBudget = 530

var allowedDirectives = []string{
	"//go:",
	"//lint:",
	"// Code generated by templ - DO NOT EDIT.",
	"// templ: version:",
}

func repoRoot(t *testing.T) string {
	t.Helper()
	root, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatalf("no se pudo resolver la raíz del repo: %v", err)
	}
	if _, err := os.Stat(filepath.Join(root, "go.mod")); err != nil {
		t.Fatalf("la raíz del repo no tiene go.mod: %v", err)
	}
	return root
}

func goFiles(t *testing.T, root string) []string {
	t.Helper()
	var out []string
	err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			switch d.Name() {
			case ".git", "node_modules", "app_scripts_v1", ".superpowers", ".claude":
				return filepath.SkipDir
			}
			return nil
		}
		if strings.HasSuffix(path, ".go") {
			out = append(out, path)
		}
		return nil
	})
	if err != nil {
		t.Fatalf("no se pudo caminar el árbol: %v", err)
	}
	sort.Strings(out)
	return out
}

func harnessMarkdown(t *testing.T, root string) []string {
	t.Helper()
	var out []string
	for _, name := range []string{"AGENTS.md", "CLAUDE.md"} {
		out = append(out, filepath.Join(root, name))
	}
	err := filepath.WalkDir(filepath.Join(root, "internal"), func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() && d.Name() == "AGENTS.md" {
			out = append(out, path)
		}
		return nil
	})
	if err != nil {
		t.Fatalf("no se pudieron listar los AGENTS.md: %v", err)
	}
	for _, name := range []string{"ARCHITECTURE.md"} {
		out = append(out, filepath.Join(root, "docs", name))
	}
	sort.Strings(out)
	return out
}

func isAllowedDirective(text string) bool {
	for _, prefix := range allowedDirectives {
		if strings.HasPrefix(text, prefix) {
			return true
		}
	}
	return false
}

func TestNoCommentsInGoSource(t *testing.T) {
	root := repoRoot(t)
	fset := token.NewFileSet()

	type finding struct {
		file string
		line int
		text string
	}
	var findings []finding

	for _, path := range goFiles(t, root) {
		file, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			t.Fatalf("no se pudo parsear %s: %v", path, err)
		}
		for _, group := range file.Comments {
			for _, comment := range group.List {
				if isAllowedDirective(comment.Text) {
					continue
				}
				rel, _ := filepath.Rel(root, path)
				findings = append(findings, finding{
					file: filepath.ToSlash(rel),
					line: fset.Position(comment.Pos()).Line,
					text: comment.Text,
				})
			}
		}
	}

	if len(findings) == 0 {
		return
	}
	t.Errorf("%d comentarios en el código. El comentario es andamio: se borra antes de commitear. Sólo sobreviven las directivas de herramienta (%s).", len(findings), strings.Join(allowedDirectives, ", "))
	for i, f := range findings {
		if i >= 10 {
			t.Errorf("  … y %d más", len(findings)-10)
			break
		}
		t.Errorf("  %s:%d  %s", f.file, f.line, firstLine(f.text))
	}
}

func firstLine(s string) string {
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		s = s[:i]
	}
	if len(s) > 70 {
		s = s[:70] + "…"
	}
	return s
}

var lineNumberRef = regexp.MustCompile(`[a-zA-Z_][a-zA-Z0-9_]*\.go:\d+`)

func TestNoLineNumberReferences(t *testing.T) {
	root := repoRoot(t)
	for _, path := range harnessMarkdown(t, root) {
		raw, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("no se pudo leer %s: %v", path, err)
		}
		rel, _ := filepath.Rel(root, path)
		scanner := bufio.NewScanner(strings.NewReader(string(raw)))
		scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
		line := 0
		for scanner.Scan() {
			line++
			for _, hit := range lineNumberRef.FindAllString(scanner.Text(), -1) {
				t.Errorf("%s:%d cita %s. Un número de línea se pudre con la próxima edición: nombrá el símbolo.", filepath.ToSlash(rel), line, hit)
			}
		}
	}
}

var (
	inlineCode  = regexp.MustCompile("`([^`]+)`")
	goFileRef   = regexp.MustCompile(`^[a-z][a-z0-9_]*\.go$`)
	goSymbolRef = regexp.MustCompile(`^[A-Za-z][A-Za-z0-9]*$`)
	hasInnerCap = regexp.MustCompile(`[a-z][A-Z]`)
)

var externalSymbols = map[string]string{
	"SendMessage":          "go-telegram/bot",
	"AnswerCallbackQuery":  "go-telegram/bot",
	"ParseModeHTML":        "go-telegram/bot/models",
	"DoUpdates":            "gorm.io/gorm/clause",
	"DoNothing":            "gorm.io/gorm/clause",
	"EscapeString":         "html",
	"additionalProperties": "JSON Schema",
}

func declaredSymbols(t *testing.T, root string) map[string]bool {
	t.Helper()
	symbols := map[string]bool{}
	fset := token.NewFileSet()
	for _, path := range goFiles(t, root) {
		file, err := parser.ParseFile(fset, path, nil, 0)
		if err != nil {
			t.Fatalf("no se pudo parsear %s: %v", path, err)
		}
		symbols[file.Name.Name] = true
		ast.Inspect(file, func(n ast.Node) bool {
			switch d := n.(type) {
			case *ast.FuncDecl:
				symbols[d.Name.Name] = true
			case *ast.TypeSpec:
				symbols[d.Name.Name] = true
			case *ast.ValueSpec:
				for _, name := range d.Names {
					symbols[name.Name] = true
				}
			case *ast.Field:
				for _, name := range d.Names {
					symbols[name.Name] = true
				}
			}
			return true
		})
	}
	return symbols
}

func goFileNames(t *testing.T, root string) map[string]bool {
	t.Helper()
	names := map[string]bool{}
	for _, path := range goFiles(t, root) {
		names[filepath.Base(path)] = true
	}
	return names
}

func TestHarnessSymbolReferencesExist(t *testing.T) {
	root := repoRoot(t)
	symbols := declaredSymbols(t, root)
	files := goFileNames(t, root)

	for _, path := range harnessMarkdown(t, root) {
		raw, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("no se pudo leer %s: %v", path, err)
		}
		rel, _ := filepath.Rel(root, path)
		scanner := bufio.NewScanner(strings.NewReader(string(raw)))
		scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
		line := 0
		for scanner.Scan() {
			line++
			for _, match := range inlineCode.FindAllStringSubmatch(scanner.Text(), -1) {
				token := match[1]
				if idx := strings.LastIndexByte(token, '.'); idx >= 0 && !strings.HasSuffix(token, ".go") {
					token = token[idx+1:]
				}
				switch {
				case goFileRef.MatchString(token):
					if !files[token] {
						t.Errorf("%s:%d cita el archivo `%s`, que no existe en el árbol.", filepath.ToSlash(rel), line, token)
					}
				case goSymbolRef.MatchString(token) && hasInnerCap.MatchString(token):
					if _, external := externalSymbols[token]; external {
						continue
					}
					if !symbols[token] {
						t.Errorf("%s:%d cita el símbolo `%s`, que no está declarado en ningún paquete.", filepath.ToSlash(rel), line, token)
					}
				}
			}
		}
	}
}

var writtenNumbers = map[string]int{
	"four": 4, "five": 5, "six": 6, "seven": 7, "eight": 8, "nine": 9,
	"ten": 10, "eleven": 11, "twelve": 12, "thirteen": 13,
	"fourteen": 14, "fifteen": 15, "sixteen": 16,
}

var packageClaim = regexp.MustCompile(`(?i)\b(four|five|six|seven|eight|nine|ten|eleven|twelve|thirteen|fourteen|fifteen|sixteen)\b\s+(?:packages?\s+)?(?:carry|stay|load|also|of the)`)

func TestPackageCountsMatchReality(t *testing.T) {
	root := repoRoot(t)

	var packages []string
	err := filepath.WalkDir(filepath.Join(root, "internal"), func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() && d.Name() == "AGENTS.md" {
			packages = append(packages, filepath.Dir(path))
		}
		return nil
	})
	if err != nil {
		t.Fatalf("no se pudieron listar los paquetes: %v", err)
	}

	rootClaude, err := os.ReadFile(filepath.Join(root, "CLAUDE.md"))
	if err != nil {
		t.Fatalf("no se pudo leer CLAUDE.md: %v", err)
	}
	alwaysLoaded := strings.Count(string(rootClaude), "@internal/")

	var stubs []string
	for _, dir := range packages {
		if _, err := os.Stat(filepath.Join(dir, "CLAUDE.md")); err == nil {
			stubs = append(stubs, dir)
		}
	}

	total := len(packages)
	onDemand := total - alwaysLoaded

	if len(stubs) != onDemand {
		t.Errorf("hay %d stubs CLAUDE.md pero %d paquetes on-demand. Un paquete always-loaded con stub carga su AGENTS.md dos veces.", len(stubs), onDemand)
		for _, dir := range stubs {
			rel, _ := filepath.Rel(root, dir)
			claudeStub := filepath.Join(dir, "CLAUDE.md")
			if strings.Contains(string(rootClaude), "@"+filepath.ToSlash(mustRel(root, claudeStub))[:len(filepath.ToSlash(mustRel(root, dir)))]+"/AGENTS.md") {
				t.Errorf("  %s tiene stub Y está importado por el CLAUDE.md raíz", filepath.ToSlash(rel))
			}
		}
	}

	valid := map[int]bool{total: true, alwaysLoaded: true, onDemand: true, len(stubs): true}
	for _, path := range harnessMarkdown(t, root) {
		raw, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("no se pudo leer %s: %v", path, err)
		}
		rel, _ := filepath.Rel(root, path)
		scanner := bufio.NewScanner(strings.NewReader(string(raw)))
		scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
		line := 0
		for scanner.Scan() {
			line++
			for _, match := range packageClaim.FindAllStringSubmatch(scanner.Text(), -1) {
				claimed := writtenNumbers[strings.ToLower(match[1])]
				if !valid[claimed] {
					t.Errorf("%s:%d afirma %q (%d). Lo real: %d paquetes, %d always-loaded, %d on-demand, %d stubs.",
						filepath.ToSlash(rel), line, strings.TrimSpace(match[0]), claimed, total, alwaysLoaded, onDemand, len(stubs))
				}
			}
		}
	}
}

func mustRel(root, path string) string {
	rel, err := filepath.Rel(root, path)
	if err != nil {
		return path
	}
	return rel
}

func TestAlwaysLoadedContextBudget(t *testing.T) {
	root := repoRoot(t)

	loaded := []string{filepath.Join(root, "CLAUDE.md"), filepath.Join(root, "AGENTS.md")}

	rootClaude, err := os.ReadFile(filepath.Join(root, "CLAUDE.md"))
	if err != nil {
		t.Fatalf("no se pudo leer CLAUDE.md: %v", err)
	}
	imports := regexp.MustCompile(`@(internal/\S+\.md)`).FindAllStringSubmatch(string(rootClaude), -1)
	for _, match := range imports {
		loaded = append(loaded, filepath.Join(root, filepath.FromSlash(match[1])))
	}

	total := 0
	report := make([]string, 0, len(loaded))
	for _, path := range loaded {
		raw, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("no se pudo leer %s: %v", path, err)
		}
		n := len(strings.Split(strings.TrimRight(string(raw), "\n"), "\n"))
		total += n
		rel, _ := filepath.Rel(root, path)
		report = append(report, fmt.Sprintf("  %5d  %s", n, filepath.ToSlash(rel)))
	}

	if total > alwaysLoadedLineBudget {
		t.Errorf("el contexto always-loaded suma %d líneas y el techo es %d. Más largo baja la adherencia, no sólo gasta contexto. El techo sólo baja: recortá, no lo subas.\n%s",
			total, alwaysLoadedLineBudget, strings.Join(report, "\n"))
	}
}

var (
	markdownLink   = regexp.MustCompile(`\[[^\]]*\]\(([^)]+)\)`)
	nonSlugRunes   = regexp.MustCompile(`[^\w\s-]`)
	spaceRune      = regexp.MustCompile(`\s`)
)

func headingSlug(heading string) string {
	s := strings.ToLower(strings.TrimSpace(strings.TrimLeft(strings.TrimSpace(heading), "#")))
	s = nonSlugRunes.ReplaceAllString(s, "")
	return strings.Trim(spaceRune.ReplaceAllString(s, "-"), "-")
}

func harnessAndDocsMarkdown(t *testing.T, root string) []string {
	t.Helper()
	seen := map[string]bool{}
	var out []string
	add := func(p string) {
		if !seen[p] {
			seen[p] = true
			out = append(out, p)
		}
	}
	for _, name := range []string{"AGENTS.md", "CLAUDE.md", "PRODUCT.md", "DESIGN.md"} {
		p := filepath.Join(root, name)
		if _, err := os.Stat(p); err == nil {
			add(p)
		}
	}
	for _, dir := range []string{"internal", "docs"} {
		err := filepath.WalkDir(filepath.Join(root, dir), func(path string, d os.DirEntry, err error) error {
			if err != nil {
				return err
			}
			if d.IsDir() && d.Name() == "superpowers" {
				return filepath.SkipDir
			}
			if !d.IsDir() && strings.HasSuffix(path, ".md") {
				add(path)
			}
			return nil
		})
		if err != nil {
			t.Fatalf("no se pudieron listar los .md de %s: %v", dir, err)
		}
	}
	sort.Strings(out)
	return out
}

func headingsOf(t *testing.T, path string) map[string]bool {
	t.Helper()
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("no se pudo leer %s: %v", path, err)
	}
	slugs := map[string]bool{}
	for _, line := range strings.Split(string(raw), "\n") {
		if strings.HasPrefix(line, "#") {
			slugs[headingSlug(line)] = true
		}
	}
	return slugs
}

func TestHarnessLinksResolve(t *testing.T) {
	root := repoRoot(t)
	files := harnessAndDocsMarkdown(t, root)

	slugs := map[string]map[string]bool{}
	for _, path := range files {
		slugs[path] = headingsOf(t, path)
	}

	for _, path := range files {
		raw, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("no se pudo leer %s: %v", path, err)
		}
		rel, _ := filepath.Rel(root, path)
		scanner := bufio.NewScanner(strings.NewReader(string(raw)))
		scanner.Buffer(make([]byte, 1024*1024), 1024*1024)
		line := 0
		for scanner.Scan() {
			line++
			for _, match := range markdownLink.FindAllStringSubmatch(scanner.Text(), -1) {
				target := match[1]
				if strings.HasPrefix(target, "http") || strings.HasPrefix(target, "mailto") || strings.HasPrefix(target, "#") {
					continue
				}
				filePart, fragment, _ := strings.Cut(target, "#")
				dest := filepath.Join(filepath.Dir(path), filepath.FromSlash(filePart))
				if _, err := os.Stat(dest); err != nil {
					t.Errorf("%s:%d enlaza a %q y ese archivo no existe.", filepath.ToSlash(rel), line, target)
					continue
				}
				known, tracked := slugs[dest]
				if fragment == "" || !tracked {
					continue
				}
				if !known[headingSlug(fragment)] {
					t.Errorf("%s:%d enlaza a %q y ese encabezado no existe. Un ancla se pudre igual que un número de línea.", filepath.ToSlash(rel), line, target)
				}
			}
		}
	}
}
