env="local"

[server]
baseHost="https://31pk7cpc-80.brs.devtunnels.ms"
port="80"

[database]
host     = "localhost"
port     = 5432
name     = "lopiibot"
user     = "lopiibot"
password = "lopiibot"
runMigrations = true

[telegram]
username="Lopiipersonalfinanceslocalbot"
token=""

[groq]
apiKey = ""
baseUrl = "https://api.groq.com/openai/v1"
routerModel = "llama-3.1-8b-instant"
createModel = "llama-3.3-70b-versatile"
updateModel = "llama-3.3-70b-versatile"
deleteModel = "llama-3.1-8b-instant"
timeoutSeconds = 20